### ISSUE TITLE
Error: Could not determine existing codeql version

### ISSUE THREAD

**Issue by Chirag1233** [microsoft/codeql-container#37] opened 2021-11-18 02:34 UTC
Hi There, 

I am trying to scan my python code on my local workstation using the Codeql container However whenI tried to run this its keep sending me the error message mention the Could not determine existing codeql version. Can you please advise me if I am doing anything wrong here? 

./analyze_security.bat C:\Temp\python\website\website C:\Temp\result python

Getting the image...
Using default tag: latest
latest: Pulling from cstsectools/codeql-container
Digest: sha256:87b399db8f3de7fc36e68f67f4d73fce8b073555411b51bd0c042b0dae0ada86
Status: Image is up to date for mcr.microsoft.com/cstsectools/codeql-container:latest
mcr.microsoft.com/cstsectools/codeql-container:latest
Pulled the container
Creating the codeQL database. This might take some time depending on the size of the project...
Could not determine existing codeql version
  File "/usr/local/startup_scripts/setup.py", line 39, in setup
    get_latest_codeql(args)
  File "/usr/local/startup_scripts/setup.py", line 44, in get_latest_codeql
    current_installed_version = codeql.get_current_local_version()
  File "/usr/local/startup_scripts/libs/codeql.py", line 74, in get_current_local_version    exit(ERROR_EXECUTING_CODEQL)NameError: name 'ERROR_EXECUTING_CODEQL' is not defined
Error 1 executing from command.Exiting...
Command Output:
[2021-11-18 01:33:59,959] INFO: Starting setup...

Failed creating the database

**Comment by InbarRose** [comment] 2021-11-18 08:55
i encountered the same issue, this is because the `mcr.microsoft.com/cstsectools/codeql-container:latest` image is over a year old and not using the latest version of the code.
and there are actually two bugs in the code that is defined there.

1. the `ERROR_EXECUTING_CODEQL` should be `self.ERROR_EXECUTING_CODEQL` (same for other errors)
2. the regex for parsing the version is wrong.

**Comment by Chirag1233** [comment] 2021-11-18 10:12
Looks like the both file is been updated in the main branch. Is that correct or not yet. The reason why I am saying that is because when I check the Codeql.py I can see the self.ERROR_EXECUTING_CODEQL. 

do you know how can I fix the regex for the parsing the version inside the setup.py currently I can see it's as this:  current_installed_version = codeql.get_current_local_version()

do we need to update that to something else? Sorry I am not an expert in this, so I thought I just check here. 

Your help is much appreciated.

**Comment by jacobmsft** [comment] 2021-11-21 15:21
Thanks Inbar, Hey Chirag, like Inbar said, the issue is fixed, and I'm trying to get the automated builds going to push the latest image to the mcr docker registry. Meanwhile, if you do a docker build on the clone of this repo, you should get the latest image without the error. It takes a couple of hours to build depending on the machine.

**Comment by Chirag1233** [comment] 2021-11-22 22:48
I will build the new image today and give it a try

**Comment by jacobmsft** [comment] 2021-11-23 17:28
Also you can pull the latest image which was updated yesterday with all the fixes. I've verified it works, I'll close this, open a new issue if problem persists.

**Closed by jacobmsft** 2021-11-23 17:28 UTC
